<?php

function acdh_repo_gui_theme($existing, $type, $theme, $path)
{
    return [
        'acdh-repo-gui-main' => [
            'variables' => ['data' => NULL, 'paging' => NULL],
        ],
        'acdh-repo-gui-detail' => [
            'variables' => ['basic' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-detail-basic' => [
            'variables' => ['basic' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-detail-persons' => [
            'variables' => ['basic' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-detail-concept' => [
            'variables' => ['basic' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-detail-project' => [
            'variables' => ['basic' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-detail-organisations' => [
            'variables' => ['basic' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-detail-places' => [
            'variables' => ['basic' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-detail-publications' => [
            'variables' => ['basic' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-detail-api' => [
            'variables' => ['helper' => NULL, 'extra' => NULL, 'dissemination' => NULL],
        ],
        'acdh-repo-gui-child' => [
            'variables' => ['data' => NULL],
        ],
        'acdh-repo-gui-main-page-left-block' => [
            'variables' => ['result' => NULL],
            
        ],
        'acdh-repo-gui-main-page-left-block-empty' => [
            'variables' => ['result' => NULL],
           
        ],
        'acdh-repo-gui-search-left-block-empty' => [
            'variables' => ['result' => NULL], 
        ],
        'arche-smart-search-view' => [
            'variables' => ['data' => NULL, 'properties' => NULL],
        ],
        'arche-smart-search-result-view' => [
            'variables' => ['data' => NULL, 'properties' => NULL],
        ],
        'acdh-repo-gui-search-left-block' => [
            'variables' => ['result' => NULL]
        ],
        'acdh-repo-gui-detail-versions-block' => [
            'variables' => ['result' => NULL]
        ],
        'acdh-repo-gui-detail-versions-block-empty' => [
            'variables' => ['result' => NULL]
        ],
        'acdh-repo-gui-detail-versions-alert' => [
            'variables' => ['result' => NULL]
        ],
        'acdh-repo-gui-vcr-block' => [
            'variables' => ['vcrUrl' => NULL]
        ],
        'acdh-repo-ds-dl-collection' => [
            'variables' => ['basic' => NULL, 'extra' => NULL],
            '#attached' => [
                'library' => [
                    'acdh_repo_gui/repo-collection-dl', 
                ]
            ]
        ],
        'acdh-repo-ds-3d-viewer' => [
            'variables' => ['ObjectUrl' => NULL, 'basic' => NULL, 'error' => NULL],
            
        ],
        'acdh-repo-ds-3d-viewer-v2' => [
            'variables' => ['ObjectUrl' => NULL, 'basic' => NULL, 'error' => NULL],
            
        ],
        'acdh-repo-ds-3d-viewer-v3' => [
            'variables' => ['ObjectUrl' => NULL, 'basic' => NULL, 'error' => NULL],
            
        ],
        'acdh-repo-ds-pdf-viewer' => [
            'variables' => ['ObjectUrl' => NULL, 'basic' => NULL],
            '#attached' => [
                'library' => [
                    'acdh_repo_gui/ds-pdf-styles', 
                ]
            ]
        ],
        'acdh-repo-ds-iiif-viewer' => [
            'variables' => ['basic' => NULL, 'lorisUrl' => NULL],
            '#attached' => [
                'library' => [
                    'acdh_repo_gui/ds-iiif-viewer-styles', 
                ]
            ]
        ],
        'helper-lng-switcher' => [
            'variables' => ['language' => NULL]
        ],
        'acdh-repo-gui-search-full' => [
            'variables' => ['data' => NULL, 'paging' => NULL, 'extra' => NULL],
            '#attached' => [
                'library' => [
                    'acdh_repo_gui/repo-search', //include our custom library for this response
                ]
            ]
            
        ],
        'acdh-repo-gui-search-full-api' => [
            'variables' => ['data' => NULL],
            '#attached' => [
                'library' => [
                    'acdh_repo_gui/repo-search', //include our custom library for this response
                ]
            ]
            
        ],
        'acdh-repo-gui-shibboleth-login' => [
            'variables' => []
        ],
        'acdh-repo-gui-detail-skos-concept' => [
            'variables' => []
        ],
        'acdh-repo-gui-detail-skos-concepschema' => [
            'variables' => []
        ],
        'arche-detail-main' => [
            'variables' => ['basic' => NULL]
        ],
        'arche-detail-overview' => [
            'variables' => ['basic' => NULL, 'tooltip' => NULL, 'dissemination' => NULL, 'clarinVCRUrl' => NULL]
        ],
        'arche-left-block-search' => [
            'variables' => ['result' => NULL]
        ],
    ];
}

// Setup custom 404!
// -> add file "page--404.html.twig" to theme template folder
function acdh_repo_gui_theme_suggestions_page(array $variables)
{
    $path_args = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));

    $suggestions = theme_get_suggestions($path_args, 'page');

    $http_error_suggestions = [
        'system.404' => 'page__404',
    ];

    $route_name = \Drupal::routeMatch()->getRouteName();

    if (isset($http_error_suggestions[$route_name])) {
        $suggestions[] = $http_error_suggestions[$route_name];
    }

    return $suggestions;
}


function acdh_repo_gui_page_attachments(array &$page) {
    $page['#attached']['drupalSettings']['acdh_repo_gui']['users']['id'] = \Drupal::currentUser()->id();
    $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $page['#attached']['drupalSettings']['acdh_repo_gui']['users']['name'] = $account->getAccountName();
    $roles = array();
    $roles = \Drupal::currentUser()->getRoles();
    if(count($roles) > 0){ $roles = implode(",", $roles); }
    $page['#attached']['drupalSettings']['acdh_repo_gui']['users']['roles'] = $roles;
}

/*
 * Create a hook for the admin form page to we can use an external javascript file
 * 
 */
function acdh_repo_gui_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
 
    //form and user permission settings for the collection download views
    $form['#attached']['library'][] = 'acdh_repo_gui/repo-collection-dl';
    
    $form['#attached']['drupalSettings']['acdh_repo_gui']['users']['id'] = \Drupal::currentUser()->id();
    $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $form['#attached']['drupalSettings']['acdh_repo_gui']['users']['name'] = $account->getAccountName();
    $roles = array();
    $roles = \Drupal::currentUser()->getRoles();
    if(count($roles) > 0){ $roles = implode(",", $roles); }
    $form['#attached']['drupalSettings']['acdh_repo_gui']['users']['roles'] = $roles;
    
    $current_path = \Drupal::service('path.current')->getPath();
    
    return $form;
}


