# This is a basic workflow to help you get started with Actions

name: phpunit

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: juampynr/drupal8ci:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: clone repo config
      run: |
        git clone --depth 1 --branch arche https://github.com/acdh-oeaw/arche-docker-config.git arche_config
        rm -f arche_config/run.d/gui.sh arche_config/run.d/oaipmh.sh arche_config/run.d/resolver.sh
        cp src/tests/src/Unit/testconfig.yaml arche_config/yaml/local.yaml
                
    - name: run repo docker
      run: |
        mkdir log
        docker run --name arche -p 80:80 -v `pwd`/log:/home/www-data/log -v `pwd`/config:/home/www-data/config -e USER_UID=`id -u` -e USER_GID=`id -g` -d acdhch/arche
    
    - name: composer update
      run: |
        composer update
        
    - name: test
      run: |
        mkdir -p build/logs
        ./vendor/phpunit/phpunit/phpunit
        
    - name: coveralls
      run: |
        export COVERALLS_RUN_LOCALLY=1
        export COVERALLS_REPO_TOKEN=${{ secrets.coverallsLocalToken }}
        composer require php-coveralls/php-coveralls
        php vendor/bin/php-coveralls -v    
