# This is a basic workflow to help you get started with Actions

name: phpunit

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
 
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: update ubuntu
      run: sudo apt-get update
      
    - name: update sqlite3
      run: sudo apt-get install sqlite3 libsqlite3-dev
      
    - name: checksqlite version
      run: sqlite3 --version
      
    - name: composer update
      run: composer update
     
    - name: composer settings
      run: |
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        echo $PATH  
        
    - name: install drupal
      run:  composer create-project drupal/recommended-project:8.8.0 drupal  
  
    - name: drupal composer update
      run: cd drupal && composer update && composer require drush/drush && composer require phpunit/phpunit ^8 && cd -
      
    - name: check drush
      run: |
        cd drupal && vendor/drush/drush/drush status && cd -
        drupal/vendor/drush/drush/drush list
    
    - name: copy sqlite db
      run: |
        mkdir -p drupal/web/sites/default/files 
        cp inst/sites/default/files/.ht.sqlite drupal/web/sites/default/files/.ht.sqlite

    - name: install drupal base with sqlite
      run: |              
        cd drupal        
        vendor/drush/drush/drush site:install standard -vvv --db-url='sqlite://sites/default/files/.ht.sqlite'
        cd -
      
    - name: copy plugin to drupal
      run: |
        mkdir -p drupal/web/modules/arche-gui
        for d in $(pwd)/*; do ln -s "$d" "drupal/web/modules/arche-gui"; done
    
    - name: check directories
      run: |
        ls -la  
        cd drupal/web/modules && ls -la
        cd arche-gui && ls -la
  
    - name: start web server
      run: |
        cd drupal && vendor/drush/drush/drush runserver 127.0.0.1:8080 &
        until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done  
        
    - name: test
      run: |
        ls -la && mkdir -p build/logs
        ./drupal/vendor/phpunit/phpunit/phpunit --version
        ./drupal/vendor/phpunit/phpunit/phpunit --configuration ./drupal/web/modules/arche-gui/phpunit.xml 
        
        echo "drupal/web/modules/arche dir build"
        cd drupal/web/modules/arche-gui/build/logs  && ls -la && cp clover.xml ./build/logs
      
        #cp drupal/web/modules/arche-gui/build/logs/clover.xml ./build/logs
        echo "main dir list"
        ls -la ./
        echo "main build dir"
        ls -la ./build/logs        
        
    - name: coveralls
      run: |
        composer require symfony/http-kernel
        composer require symfony/process
        composer require symfony/lock
        composer require symfony/event-dispatcher
        composer fund
        export COVERALLS_RUN_LOCALLY=1
        export COVERALLS_REPO_TOKEN=${{ secrets.coverallsLocalToken }}
        composer require php-coveralls/php-coveralls
        php vendor/bin/php-coveralls -v    
